custom_target(
    'main.js',
    input: ['main.js', 'interop.js', bundle_target[0], lite_exe],
    output: ['main.js', 'main.js.map'],
    depends: [bundle_target],
    depend_files: ['zipfile.js', 'interop.js', 'utils.js'],
    install: true,
    install_dir: lite_bindir,
    install_tag: ['shell'],
    command: [
        esbuild_exe,
        '--bundle',
        '--minify',
        '--target=es2017',
        '@INPUT0@',
        '--alias:wasm-interop=./@INPUT1@',
        '--alias:asset-loader=./@INPUT2@',
        '--alias:lite-xl=./@INPUT3@',
        '--outfile=@OUTPUT0@',
        '--sourcemap=linked',
    ],
)

custom_target(
    'advanced.js',
    input: 'advanced.js',
    output: 'advanced.js',
    build_by_default: true,
    install: true,
    install_dir: lite_bindir,
    install_tag: ['shell'],
    command: [
        esbuild_exe,
        '--bundle',
        '--minify',
        '--target=es2017',
        '@INPUT0@',
        '--outfile=@OUTPUT@',
        '--sourcemap=linked',
    ],
)