#!/usr/bin/env bash

# here we get a list of symbols imported by the module, excluding:
# - memory and table imports
# - get/setTempRet0 (those are exported by JS)
# - __asyncjs calls (those are also exported by JS)
# - idbsync* (my function)
read -r -d '' awk_command <<'EOF'
{
    if ($1 == "(import"
        && $4 !~ /\((memory|table)/
        && $3 !~ /^"(get|set)TempRet0/
        && $3 !~ /^"idbsync/
        && $3 !~ /^"__asyncjs/) {
        print "_" substr($3, 2, length($3)-2)
    }
}
EOF
awk_command="$(printf '%s' "$awk_command" | tr -d '\n')"

generate_list() {
    for f in "$@"; do
        wasm-dis "$f" | awk "$awk_command"
    done
}


output="$1"; shift

list="_main,$(generate_list "$@" | tr '\n' ',')"
list="${list%,*}"

cat << EOF > "$output"
# autogenerated by $0, do not modify
[constants]
exported_functions = '$list'
EOF
